name: ciipro-env-1-1-19
channels: !!python/tuple
- rdkit
- mwojcikowski
- anaconda
- defaults
dependencies:
- bokeh=0.11.1
- bzip2=1.0.6
- click=6.6
- flask=0.11.1
- flask-login=0.3.2
- itsdangerous=0.24
- jinja2=2.8
- markupsafe=0.23
- mkl=11.3.3
- zlib=1.2.8
- numpy=1.11.1
- pandas=0.18.1
- pip=8.1.2
- pymongo=3.3.0
- python=3.4.3=0
- python-dateutil=2.5.3
- pytz=2016.6.1
- pyyaml=3.12
- rdkit=2016.03.1
- requests=2.11.1
- scipy=0.18.0
- setuptools=27.2.0
- six=1.10.0
- sqlalchemy=1.0.13
- tornado=4.4.1
- werkzeug=0.11.11
- wheel=0.29.0
- et_xmlfile=1.0.1
- jdcal=1.2
- openpyxl=2.3.2
- nose=1.3.7
- pip:
  - flask-sqlalchemy==2.1
  - flask-script==2.0.5


